apiVersion: apps/v1
kind: Deployment
metadata:
  name: skaffold-pod
  namespace: monitor
  labels:
    app: skaffold-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skaffold-pod
  template:
    metadata:
      labels:
        app: skaffold-pod
    spec:
      containers:
      - name: skaffold-pod
        image: registry.test.tjiptv.net/test/skf
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 0.5
            memory: 1Gi
          limits:
            cpu: 1
            memory: 2Gi


